[indi]
host = "127.0.0.1"
port = 7624

[solver]
name = "astap"
binary = "astap_cli"
database_path = "~/.astap"
search_radius_deg = 5.0

[site]
latitude_deg = -34.93
longitude_deg = 138.60
elevation_m = 50
